### PR TITLE
fix https://github.com/LeaVerou/contrast-ratio/issues/10

### PR DESCRIPTION
**Pull request by chrisjshull**

### CODE REVIEW

**Comment by ChrisBoon** [comment]
The issue here is that both the current live version and this proposed fix rely on 'magic numbers' to  position the text. 
The misalignment occurs due to the changing typeface - the css specifies 'sans-serif' so different browsers/OS will supply different fonts, users can customize these defaults, and even with the same font there may be some rendering differences caused by OS/browser.

For example when I view both the current live version and this fork in Firefox I still have alignment issues with the logo.

It doesn't seem like there is an easy way to fix this with the current mark-up. It's likely that replacing the text with an SVG would be the easiest approach.

I did figure out a way to achieve it by just adjusting the CSS and still aligning correctly regardless of font-family, size, or even text included (see reduced test case: http://codepen.io/chrisboon27/pen/dXqXBP ) but it relies on a fairly hacky approach, that I wouldn't personally want to put into a production environment.

**Comment by chrisjshull** [comment]
I've switched it over to flexbox, which should make it work regardless of font.

**Comment by LeaVerou** [comment]
It also completely changed the design, which I guess you didn't think was important enough to mention?!

**Comment by chrisjshull** [comment]
It shouldn't have. It certainly wan't intended. Can you attach a screenshot of what you saw?

**Comment by chrisjshull** [comment]
oh, rats. I see it now. I was working in a very narrow window before. Easy fix. 1 sec...

**Comment by chrisjshull** [comment]
... https://github.com/LeaVerou/contrast-ratio/pull/23

**Review by whiteslack — APPROVED** [review]
whiteslack

**Pull request merged**
