### PR TITLE
Updating home page with some Italic styled text.

### PR DESCRIPTION
**Pull request by SwastikGowdaL**
Sometimes even though the Color contrast is slightly off, still the text looks kinda good when its italic. So i've added some text with italic style so the user can see how text looks in various styles.

### CODE REVIEW

**Comment by SethFalco** [comment]
The `em` tag in HTML is not a proper way to set text to italic. It tells browsers to place emphasis on the text. Just because most browsers do this by making the text italic doesn't mean it should be used for the sole purpose of making text italic.

> Typically this element is displayed in italic type. However, it should not be used simply to apply italic styling; use the CSS font-style property for that purpose.
> - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em

It's also worth noting the `<i>` tag shouldn't be used either because according to MDN web docs:
> In earlier versions of the HTML specification, the \<i> element was merely a presentational element used to display text in italics, much like the \<b> element was used to display text in bold letters. This is no longer true, as these tags now define semantics rather than typographic appearance. A browser will typically still display the contents of the \<i> element in italic type, but is, by definition, no longer required to do so. To display text in italic type, authors should use the CSS font-style property.
> - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i

This should be done by using the CSS [`font-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style) property.

**Comment by LeaVerou** [comment]
Agreed, a paragraph would be more appropriate there with `font-style: italic;`

**Comment by LeaVerou** [comment]
Thanks!

**Comment by LeaVerou** [comment]
actually, I've just realized: we don't have an entire new paragraph for bold, only a bold word. We could do the same with italic, since now the text is a bit too long.
i.e. "This sample text attempts to visually demonstrate how readable this color combination is, for normal, italic, bold, or bold italic text of various sizes and font styles."

**Pull request merged**
